name: MeepCore
main: io.github.meeples10.meepcore.Main
version: 1.3.2
author: Meeples10
description: API for Meeples10's plugins.
api-version: 1.14
commands:
  meepcore:
    description: Base command for MeepCore
    usage: /meepcore