name: MeepCore
main: io.github.meeples10.meepcore.Main
version: 1.2.0
author: Meeples10
description: API for Meeples10's plugins.
commands:
  meepcore:
    description: Base command for MeepCore
    usage: /meepcore