# The color scheme of MeepCore and the plugins that depend on it
# 0 for MeepCore style
# 1 for Essentials style
# 2 for muted style
color-scheme: 0

# If a language file is not found for a player's locale,
# the plugin will fall back to this language
fallback-locale: en_US
